### ISSUE TITLE
2.x ToDo List

### ISSUE THREAD

**Issue by Panman8201** [froala/ember-froala-editor#1]
Just a few things that could be changed once we can support Ember 2.5+. Maybe we could follow Ember's versions with support.?. (eg; Addon version 2.5.x requires Ember.js 2.5.x)
- [x] Replace `Object.assign()` with `Ember.assign()` ([added in Ember 2.5](http://emberjs.com/blog/2016/02/29/ember-2-4-released.html#toc_code-ember-assign-code)) and remove the Babel polyfil requirement
- [ ] Combine the `options` and `defaultOptions` properties, [will work properly with the release of Ember 2.4.2](https://github.com/emberjs/ember.js/pull/13031)
- [x] Move to [ember-font-awesome 2.x](https://github.com/martndemus/ember-font-awesome) which has some Ember 2.x changes but requires Ember 2.3

**Comment by cibernox** [comment]
@Panman8201 Wait a bit before using `Ember.assign`. I raised a question of why adding another `Ember.keys` functionality just to deprecate it in not a long time. It's going to be discussed once more.
Just hold on a little bit until it's in stable.

**Comment by Panman8201** [comment]
@cibernox While I agree that Babel really has taken the place for needing to add polyfills directly to Ember, it would be nice not needing to _force_ users to include the Babel polyfill. Do you have a link to the discussion?

**Comment by Panman8201** [comment]
In order to move away from the Babel polyfill requirement, I've added an `if` statement to look for the new `Ember.assign()` polyfill or else fall-back to an `Ember.merge()` way of filling the need.
